import type { Dispatch, SetStateAction } from 'react';
import { saveBeatmap, submitBeatmapUpdateRequest } from '../../core/api/client';
import type { SongDetail, ChordLyric, GuitarTabLine } from '../../core/api/client';
import { parseChordsFromLine, isTabLine, getBeatCycle, stepBeat } from './songUtils';

interface BeatmapEditorModalProps {
  contentLines: (ChordLyric | GuitarTabLine)[];
  beatmapDraft: number[];
  setBeatmapDraft: Dispatch<SetStateAction<number[]>>;
  beatmapSubmitSuccess: boolean;
  setBeatmapSubmitSuccess: Dispatch<SetStateAction<boolean>>;
  activeSongId: string | null;
  song: SongDetail | null;
  setBeatmap: Dispatch<SetStateAction<number[] | null>>;
  setBeatmapAutoGenerated: Dispatch<SetStateAction<boolean>>;
  setShowBeatmapEditor: Dispatch<SetStateAction<boolean>>;
}

export default function BeatmapEditorModal({
  contentLines, beatmapDraft, setBeatmapDraft,
  beatmapSubmitSuccess, setBeatmapSubmitSuccess,
  activeSongId, song,
  setBeatmap, setBeatmapAutoGenerated, setShowBeatmapEditor,
}: BeatmapEditorModalProps) {
  const beatCycle = getBeatCycle(song?.timeSignature ?? 4);

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/40" onClick={() => setShowBeatmapEditor(false)}>
      <div className="bg-white rounded-2xl shadow-xl w-full max-w-2xl max-h-[80vh] flex flex-col mx-4" onClick={e => e.stopPropagation()}>
        <div className="flex items-center justify-between px-5 py-3 border-b border-gray-100 shrink-0">
          <span className="font-semibold text-sm text-gray-800">Beat Map</span>
          <button onClick={() => setShowBeatmapEditor(false)} className="text-gray-400 hover:text-gray-600 text-lg leading-none">✕</button>
        </div>

        <div className="overflow-y-auto flex-1 px-5 py-3 flex flex-col gap-3">
          {(() => {
            let offset = 0;
            return contentLines.map((line, li) => {
              if (isTabLine(line)) return null;
              const tokens = parseChordsFromLine((line as ChordLyric).chords);
              if (!tokens.length) return null;
              const start = offset;
              offset += tokens.length;
              return (
                <div key={li} className="flex flex-col gap-1">
                  <div className="flex items-center gap-3 flex-wrap">
                    {tokens.map((chord, ci) => {
                      const val = beatmapDraft[start + ci] ?? 4;
                      const set = (v: number) => setBeatmapDraft(d => { const n = [...d]; n[start + ci] = Math.max(0, Math.min(16, v)); return n; });
                      return (
                        <div key={ci} className="flex flex-col items-center gap-1">
                          <span className="font-mono text-xs text-brand-6">{chord}</span>
                          <div className="flex items-center gap-1">
                            <button onClick={() => set(stepBeat(val, -1, beatCycle))} className="w-7 h-7 flex items-center justify-center text-sm border border-gray-200 rounded text-gray-500 hover:bg-gray-100 active:bg-gray-200">−</button>
                            <span className="w-6 text-center text-xs tabular-nums">{val}</span>
                            <button onClick={() => set(stepBeat(val, 1, beatCycle))} className="w-7 h-7 flex items-center justify-center text-sm border border-gray-200 rounded text-gray-500 hover:bg-gray-100 active:bg-gray-200">+</button>
                          </div>
                        </div>
                      );
                    })}
                  </div>
                  {(line as ChordLyric).lyrics?.trim() && (
                    <span className="font-mono text-xs text-gray-400 pl-0.5">{(line as ChordLyric).lyrics.trimEnd()}</span>
                  )}
                </div>
              );
            });
          })()}
        </div>

        <div className="flex flex-col gap-2 px-5 py-3 border-t border-gray-100 shrink-0">
          {beatmapSubmitSuccess && (
            <p className="text-xs text-success-6">Beatmap update submitted for review.</p>
          )}
          <div className="flex gap-2">
            <button
              onClick={() => {
                if (!activeSongId) return;
                const beats = beatmapDraft.map(v => v ?? 4);
                if (song?.ownedByCurrentUser) {
                  saveBeatmap(activeSongId, beats)
                    .then(() => {
                      setBeatmap(beatmapDraft);
                      setBeatmapAutoGenerated(false);
                      setShowBeatmapEditor(false);
                    })
                    .catch(() => {});
                } else {
                  submitBeatmapUpdateRequest(activeSongId, beats)
                    .then(() => { setBeatmapSubmitSuccess(true); })
                    .catch(() => {});
                }
              }}
              className="px-4 py-1.5 text-xs rounded-lg bg-brand-6 text-white hover:bg-brand-7 transition-colors font-medium"
            >
              {song?.ownedByCurrentUser ? 'Save' : 'Submit for review'}
            </button>
            <button
              onClick={() => { setShowBeatmapEditor(false); setBeatmapSubmitSuccess(false); }}
              className="px-4 py-1.5 text-xs rounded-lg border border-gray-300 text-gray-600 hover:bg-gray-50 transition-colors"
            >
              Cancel
            </button>
          </div>
        </div>
      </div>
    </div>
  );
}
