import type { Dispatch, SetStateAction } from 'react';

interface SongControlsContentProps {
  localSemitones: number;
  setLocalSemitones: Dispatch<SetStateAction<number>>;
  setNeckRefresh: Dispatch<SetStateAction<number>>;
  beatmap: number[] | null;
  beatmapAutoGenerated: boolean;
  showBeatmapEditor: boolean;
  setShowBeatmapEditor: Dispatch<SetStateAction<boolean>>;
  setBeatmapDraft: Dispatch<SetStateAction<number[]>>;
  lickModeEnabled: boolean;
  lickSpeed: number;
  setLickSpeed: Dispatch<SetStateAction<number>>;
}

export default function SongControlsContent({
  localSemitones, setLocalSemitones, setNeckRefresh,
  beatmap, beatmapAutoGenerated, showBeatmapEditor, setShowBeatmapEditor, setBeatmapDraft,
  lickModeEnabled, lickSpeed, setLickSpeed,
}: SongControlsContentProps) {
  return (
    <>
      <div className="flex items-center gap-1">
        <span className="text-xs text-gray-400">Transpose</span>
        <button
          onClick={() => { setLocalSemitones(s => s - 1); setNeckRefresh(n => n + 1); }}
          className="w-6 h-6 flex items-center justify-center text-sm text-gray-500 hover:text-brand-5 border border-gray-200 rounded"
        >−</button>
        <span className="text-sm text-gray-700 w-6 text-center tabular-nums">
          {localSemitones > 0 ? `+${localSemitones}` : localSemitones}
        </span>
        <button
          onClick={() => { setLocalSemitones(s => s + 1); setNeckRefresh(n => n + 1); }}
          className="w-6 h-6 flex items-center justify-center text-sm text-gray-500 hover:text-brand-5 border border-gray-200 rounded"
        >+</button>
      </div>

      {beatmap && (
        <div className="flex items-center gap-1.5">
          <button
            onClick={() => { setBeatmapDraft([...beatmap]); setShowBeatmapEditor(v => !v); }}
            className={`px-2 py-0.5 text-xs rounded border transition-colors ${showBeatmapEditor ? 'border-brand-4 text-brand-6 bg-brand-1' : 'border-gray-300 text-gray-600 hover:bg-gray-50'}`}
          >
            Beat Map
          </button>
          {beatmapAutoGenerated && (
            <span className="text-xs text-warn-4" title="Auto-generated — may be inaccurate">⚠ auto</span>
          )}
        </div>
      )}

      {lickModeEnabled && (
        <div className="flex items-center gap-1.5">
          <span className="text-xs text-gray-400">Lick</span>
          {[1, 2, 4].map(s => (
            <button
              key={s}
              onClick={() => setLickSpeed(s)}
              className={`px-1.5 py-0.5 text-xs rounded border transition-colors ${lickSpeed === s ? 'border-brand-4 text-brand-6 bg-brand-1' : 'border-gray-300 text-gray-500 hover:bg-gray-50'}`}
            >
              {s === 1 ? '1×' : s === 2 ? '½×' : '¼×'}
            </button>
          ))}
        </div>
      )}
    </>
  );
}
