import { useState, useEffect, useMemo, useRef } from 'react';
import type { MutableRefObject, Dispatch, SetStateAction } from 'react';
import { getSong, getChordVoicings, getBeatmap, saveBeatmap } from '../../core/api/client';
import type { SongDetail, SongSummary, ChordLyric, GuitarTabLine, ChordVoicing } from '../../core/api/client';
import { parseTabString, buildDotsForColumn } from '../licks/lickUtils';
import type { TabColumn } from '../licks/lickUtils';
import { useMetronomeContext } from '../../core/metronome/MetronomeContext';
import { CHROMATIC_NOTES, getStringLabels, formatKeyWithMode } from '../../core/music';
import type { InstrumentName } from '../../core/useInstrument';
import { parseChordName } from '../songs/parseChordName';
import {
  parseChordsFromLine, totalHalfBeats, halfBeatsPerChord,
  generateBeatmap, isTabLine, isSectionHeader,
} from './songUtils';

interface UseSongModeInput {
  instrument: InstrumentName;
  isActive: boolean;
  urlSongId: string | null;
  urlSemitones: number;
  urlCapo: number;
  urlTempoOverride: number | null;
  setBpmInput: (v: string) => void;
  setCachedVoicings: Dispatch<SetStateAction<Record<string, ChordVoicing[]>>>;
  onSetSongMode: () => void;
  halfBeatRef: MutableRefObject<number>;
}

export function useSongMode({
  instrument, isActive, urlSongId, urlSemitones, urlCapo, urlTempoOverride,
  setBpmInput, setCachedVoicings, onSetSongMode, halfBeatRef,
}: UseSongModeInput) {
  const { isPlaying, setIsPlaying, setBeatsPerBar } = useMetronomeContext();

  const [song, setSong] = useState<SongDetail | null>(null);
  const [activeSongId, setActiveSongId] = useState<string | null>(urlSongId);
  const [currentIdx, setCurrentIdx] = useState(0);
  const [intraChordIdx, setIntraChordIdx] = useState(0);
  const [beatInChord, setBeatInChord] = useState(0);
  const [lickModeEnabled, setLickModeEnabled] = useState(false);
  const [lickSpeed, setLickSpeed] = useState(1);
  const [guitarKaraokeMode, setGuitarKaraokeMode] = useState(false);
  const [localSemitones, setLocalSemitones] = useState(urlSemitones);
  const [localCapo, setLocalCapo] = useState(urlCapo);
  const [showLibrary, setShowLibrary] = useState(false);
  const [beatmap, setBeatmap] = useState<number[] | null>(null);
  const [beatmapAutoGenerated, setBeatmapAutoGenerated] = useState(false);
  const [showBeatmapEditor, setShowBeatmapEditor] = useState(false);
  const [beatmapDraft, setBeatmapDraft] = useState<number[]>([]);
  const [beatmapSubmitSuccess, setBeatmapSubmitSuccess] = useState(false);

  const [loadedViaUrl, setLoadedViaUrl] = useState(!!urlSongId);
  const prevSongIdForPrefill = useRef<string | null>(null);
  const beatmapFetchedForRef = useRef<string | null>(null);

  const showBackLink = !!(activeSongId && loadedViaUrl && urlSongId === activeSongId);

  useEffect(() => {
    if (!activeSongId || !isActive) return;
    getSong(activeSongId, localSemitones).then(s => {
      setSong(s);
      setCurrentIdx(0);
      if (s.timeSignature) setBeatsPerBar(s.timeSignature);
      if (prevSongIdForPrefill.current !== activeSongId) {
        prevSongIdForPrefill.current = activeSongId;
        setBpmInput(String(urlTempoOverride ?? s.tempo ?? 120));
        if (!loadedViaUrl) setLocalCapo(s.capo ?? 0);
      }
    }).catch(() => {});
  }, [activeSongId, localSemitones, isActive]);

  const { contentLines, tabLineMap, tabOrderMap } = useMemo(() => {
    const lines: (ChordLyric | GuitarTabLine)[] = [];
    const map = new Map<ChordLyric, GuitarTabLine>();
    const orderMap = new Map<GuitarTabLine, number>();
    let tabIdx = 0;
    for (const l of song?.chordLines ?? []) {
      if (!isTabLine(l)) {
        const cl = l as ChordLyric;
        if (cl.chords.trim() || cl.lyrics.trim()) lines.push(cl);
        continue;
      }
      orderMap.set(l, tabIdx++);
      if (l.header.trim()) {
        const synth: ChordLyric = { chords: l.header, lyrics: '', fontSize: l.fontSize };
        lines.push(synth);
        map.set(synth, l);
      } else if (lickModeEnabled) {
        lines.push(l);
      }
    }
    return { contentLines: lines, tabLineMap: map, tabOrderMap: orderMap };
  }, [song, lickModeEnabled]);

  const tabColumnsByTab = useMemo(() => {
    const map = new Map<GuitarTabLine, TabColumn[]>();
    (song?.chordLines ?? []).filter(isTabLine).forEach(l => {
      const tIdx = tabOrderMap.get(l);
      const rawTab = (tIdx !== undefined && song?.songLicks?.[tIdx]?.rawTab)
        ? song.songLicks[tIdx].rawTab
        : l.tabLines.join('\n');
      map.set(l, parseTabString(rawTab));
    });
    return map;
  }, [song, tabOrderMap]);

  useEffect(() => {
    if (!activeSongId || !isActive || !contentLines.length) return;
    if (beatmapFetchedForRef.current === activeSongId) return;
    beatmapFetchedForRef.current = activeSongId;
    setBeatmap(null);
    getBeatmap(activeSongId)
      .then(data => {
        const beats = data.beats;
        const expected = contentLines
          .filter(l => !isTabLine(l))
          .reduce((n, l) => n + parseChordsFromLine((l as ChordLyric).chords).length, 0);
        if (beats.length < expected) {
          const chordOnlyLines = contentLines.filter(l => !isTabLine(l)) as ChordLyric[];
          const generated = generateBeatmap(chordOnlyLines, song?.timeSignature ?? 4);
          setBeatmap(generated);
          setBeatmapAutoGenerated(true);
          if (song?.ownedByCurrentUser) saveBeatmap(activeSongId, generated).catch(() => {});
        } else {
          setBeatmap(beats);
          setBeatmapAutoGenerated(false);
        }
      })
      .catch(() => {
        const chordOnlyLines = contentLines.filter(l => !isTabLine(l)) as ChordLyric[];
        const generated = generateBeatmap(chordOnlyLines, song?.timeSignature ?? 4);
        setBeatmap(generated);
        setBeatmapAutoGenerated(true);
        if (song?.ownedByCurrentUser) saveBeatmap(activeSongId, generated).catch(() => {});
      });
  }, [activeSongId, isActive, contentLines]);

  useEffect(() => {
    if (!contentLines.length) return;
    const unique = [...new Set(contentLines.flatMap(l =>
      isTabLine(l) ? [] : parseChordsFromLine((l as ChordLyric).chords)
    ))];
    setCachedVoicings({});
    Promise.all(
      unique.map(async name => {
        const parsed = parseChordName(name);
        if (!parsed) return [name, []] as const;
        const voicings = await getChordVoicings(parsed.root, parsed.quality, instrument);
        return [name, voicings] as const;
      })
    ).then(results => setCachedVoicings(Object.fromEntries(results)))
     .catch(() => {});
  }, [contentLines, instrument]);

  const beatmapByLine = useMemo((): number[][] | null => {
    if (!beatmap) return null;
    let offset = 0;
    return contentLines.map(l => {
      if (isTabLine(l)) {
        const cols = tabColumnsByTab.get(l) ?? [];
        return cols.map(() => lickSpeed);
      }
      const n = parseChordsFromLine((l as ChordLyric).chords).length;
      const slice = beatmap.slice(offset, offset + n).map(b => Math.max(0, b));
      offset += n;
      return slice;
    });
  }, [beatmap, contentLines, tabColumnsByTab, lickSpeed]);

  const { soundingRoot, shapeRoot, soundingMode } = useMemo(() => {
    if (!song) return { soundingRoot: '', shapeRoot: '', soundingMode: 'IONIAN' };
    const root = song.originalKey ?? 'C';
    const mode = song.mode ?? 'IONIAN';
    const idx = CHROMATIC_NOTES.indexOf(root);
    if (idx === -1) return { soundingRoot: root, shapeRoot: root, soundingMode: mode };
    const soundingIdx = ((idx + localSemitones + localCapo - (song.capo ?? 0)) % 12 + 12) % 12;
    const shapeIdx    = ((idx + localSemitones            - (song.capo ?? 0)) % 12 + 12) % 12;
    return { soundingRoot: CHROMATIC_NOTES[soundingIdx], shapeRoot: CHROMATIC_NOTES[shapeIdx], soundingMode: mode };
  }, [song, localSemitones, localCapo]);

  const keyDisplay = useMemo(() => {
    if (!song?.originalKey) return '';
    return formatKeyWithMode(soundingRoot, song.mode ?? 'IONIAN');
  }, [song, soundingRoot]);

  const activeChord = useMemo(() => {
    if (!contentLines.length) return null;
    const line = contentLines[currentIdx];
    if (!line || isTabLine(line)) return null;
    const tokens = parseChordsFromLine((line as ChordLyric).chords);
    const token = tokens[intraChordIdx] ?? tokens[0] ?? null;
    if (token === 'NC' || token === 'N.C.') return null;
    return token;
  }, [contentLines, currentIdx, intraChordIdx]);

  const nextActiveChord = useMemo(() => {
    if (!contentLines.length) return null;
    const line = contentLines[currentIdx];
    if (!line || isTabLine(line)) return null;
    const tokens = parseChordsFromLine((line as ChordLyric).chords);
    for (let j = intraChordIdx + 1; j < tokens.length; j++) {
      if (tokens[j] !== 'NC' && tokens[j] !== 'N.C.') return tokens[j];
    }
    for (let i = currentIdx + 1; i < contentLines.length; i++) {
      const cl = contentLines[i];
      if (isTabLine(cl)) continue;
      if (!isSectionHeader(cl as ChordLyric)) {
        const t = parseChordsFromLine((cl as ChordLyric).chords);
        const next = t.find(x => x !== 'NC' && x !== 'N.C.');
        if (next) return next;
      }
    }
    return null;
  }, [contentLines, currentIdx, intraChordIdx]);

  const karaokeChordIdx = useMemo(() => {
    if (!contentLines[currentIdx] || isTabLine(contentLines[currentIdx])) return undefined;
    return intraChordIdx;
  }, [contentLines, currentIdx, intraChordIdx]);

  const currentChordBeats = (() => {
    if (!isPlaying) return 0;
    const line = contentLines[currentIdx];
    if (lickModeEnabled && line && isTabLine(line)) {
      return tabColumnsByTab.get(line)?.length ?? 0;
    }
    return beatmapByLine?.[currentIdx]?.[intraChordIdx] ?? 0;
  })();

  const nextChordBeats = useMemo(() => {
    if (!isPlaying || !beatmapByLine) return 0;
    const lineBeats = beatmapByLine[currentIdx];
    if (lineBeats && intraChordIdx + 1 < lineBeats.length) return lineBeats[intraChordIdx + 1];
    return beatmapByLine[currentIdx + 1]?.[0] ?? 0;
  }, [isPlaying, beatmapByLine, currentIdx, intraChordIdx]);

  const lickOverlayDots = useMemo(() => {
    if (!lickModeEnabled) return null;
    const line = contentLines[currentIdx];
    if (!line) return null;

    let tabLine: GuitarTabLine | null = null;
    let colIdx = 0;

    if (isTabLine(line)) {
      tabLine = line;
      colIdx = intraChordIdx;
    } else {
      const associated = tabLineMap.get(line as ChordLyric);
      if (!associated) return null;
      tabLine = associated;
      const cols = tabColumnsByTab.get(tabLine);
      const N = cols?.length ?? 1;
      const M = Math.max(1, parseChordsFromLine((line as ChordLyric).chords).length);
      const lineDist = beatmapByLine?.[currentIdx];
      let absHalfBeat: number;
      let totalHB: number;
      if (lineDist && lineDist.length > 0) {
        const priorBeats = lineDist.slice(0, intraChordIdx).reduce((a, b) => a + b, 0);
        absHalfBeat = priorBeats + Math.max(0, beatInChord - 1);
        totalHB = lineDist.reduce((a, b) => a + b, 0);
      } else {
        absHalfBeat = intraChordIdx;
        totalHB = M;
      }
      colIdx = Math.min(Math.floor(absHalfBeat * N / Math.max(1, totalHB)), N - 1);
    }

    const cols = tabColumnsByTab.get(tabLine);
    if (!cols) return null;
    const col: TabColumn = cols[colIdx] ?? { isRest: true as const };
    const stringCount = getStringLabels(instrument).length;
    const raw = buildDotsForColumn(col, stringCount);
    if (localCapo === 0) return raw;
    return raw.map(string => {
      const len = string.length;
      const shifted = Array.from({ length: len }, () => ({ degree: null as null, active: false }));
      string.forEach((dot, fret) => {
        const physFret = fret + localCapo;
        if (dot.active && physFret < len) {
          shifted[physFret] = { degree: 1 as const, active: true };
        }
      });
      return shifted;
    });
  }, [lickModeEnabled, contentLines, currentIdx, intraChordIdx, beatInChord, beatmapByLine, tabColumnsByTab, tabLineMap, localCapo, instrument]);

  const karaokeLines = useMemo(
    () => contentLines.map((l): ChordLyric =>
      isTabLine(l) ? { chords: '', lyrics: '[lick playing]', fontSize: 14 } : l as ChordLyric
    ),
    [contentLines]
  );

  const advanceSongRef = useRef<() => void>(() => {});
  advanceSongRef.current = () => {
    if (!contentLines.length) return;
    const line = contentLines[currentIdx];
    const isTab = line != null && isTabLine(line);
    let dist: number[];
    if (isTab) {
      dist = beatmapByLine?.[currentIdx] ?? (tabColumnsByTab.get(line as GuitarTabLine) ?? []).map(() => lickSpeed);
    } else {
      const chords = (line as ChordLyric)?.chords ?? '';
      const tokens = parseChordsFromLine(chords);
      dist = beatmapByLine?.[currentIdx] ?? halfBeatsPerChord(tokens.length, totalHalfBeats(chords));
    }
    const total = dist.reduce((a, b) => a + b, 0);
    halfBeatRef.current++;
    if (halfBeatRef.current > total || total === 0) {
      halfBeatRef.current = 1;
      setBeatInChord(1);
      setIntraChordIdx(0);
      setCurrentIdx(i => {
        let next = (i + 1) % contentLines.length;
        let guard = 0;
        while (
          !isTabLine(contentLines[next]) &&
          isSectionHeader(contentLines[next] as ChordLyric) &&
          guard < contentLines.length
        ) {
          next = (next + 1) % contentLines.length;
          guard++;
        }
        return next;
      });
      return;
    }
    let accum = 0;
    let newSlotIdx = Math.max(0, dist.length - 1);
    for (let i = 0; i < dist.length; i++) {
      accum += dist[i];
      if (halfBeatRef.current <= accum) { newSlotIdx = i; break; }
    }
    const priorBeats = dist.slice(0, newSlotIdx).reduce((a, b) => a + b, 0);
    setBeatInChord(isTab ? newSlotIdx + 1 : halfBeatRef.current - priorBeats);
    setIntraChordIdx(newSlotIdx);
  };

  function loadSongById(summary: SongSummary) {
    setShowLibrary(false);
    setIsPlaying(false);
    setLoadedViaUrl(false);
    setSong(null);
    setActiveSongId(summary.id);
    setLocalSemitones(0);
    setLocalCapo(summary.capo ?? 0);
    onSetSongMode();
    setCurrentIdx(0);
    halfBeatRef.current = 0;
    setIntraChordIdx(0);
    beatmapFetchedForRef.current = null;
    setBeatmap(null);
    setShowBeatmapEditor(false);
  }

  return {
    song,
    activeSongId,
    currentIdx, setCurrentIdx,
    intraChordIdx, setIntraChordIdx,
    beatInChord, setBeatInChord,
    lickModeEnabled, setLickModeEnabled,
    lickSpeed, setLickSpeed,
    guitarKaraokeMode, setGuitarKaraokeMode,
    localSemitones, setLocalSemitones,
    localCapo, setLocalCapo,
    showLibrary, setShowLibrary,
    beatmap, setBeatmap,
    beatmapAutoGenerated, setBeatmapAutoGenerated,
    showBeatmapEditor, setShowBeatmapEditor,
    beatmapDraft, setBeatmapDraft,
    beatmapSubmitSuccess, setBeatmapSubmitSuccess,
    contentLines, tabLineMap, tabOrderMap,
    tabColumnsByTab,
    beatmapByLine,
    lickOverlayDots,
    karaokeLines,
    karaokeChordIdx,
    currentChordBeats,
    nextChordBeats,
    soundingRoot, shapeRoot, soundingMode,
    keyDisplay,
    activeChord, nextActiveChord,
    showBackLink,
    loadSongById,
    advance: () => advanceSongRef.current(),
  };
}
